#!/usr/bin/env python3

import json
import locale
import sys
import operator
import reports
import emails
import os

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"total_sales": 0}
  years = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # Calculate the car model which had the most sales by completing the process_data method
    # and then appending a formatted string to the summary list 
    if item["total_sales"] > max_sales["total_sales"]:
      max_sales = item
    # Calculate the most popular car_year across all car make/models
    # (in other words, find the total count of cars with the car_year equal to 2005, equal to 2006, etc.
    # and then figure out the most popular year) by completing the process_data method
    # and append a formatted string to the summary
    if item["car"]["car_year"] not in years:
      years[item["car"]["car_year"]] = item["total_sales"]
    else:
      years[item["car"]["car_year"]] = years[item["car"]["car_year"]] + item["total_sales"]

  max_year = {}
  max_year["year"] = max(years.items(), key=operator.itemgetter(1))[0]
  max_year["total_sales"] = max(years.items(), key=operator.itemgetter(1))[1]

  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(
      format_car(max_sales["car"]), max_sales["total_sales"]),
    "The most popular year was {} with {} sales.".format(
      max_year["year"], max_year["total_sales"])
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  
  # Turn this into a PDF report
  summary_l = ""
  for elem in summary:
    summary_l = summary_l + elem + "<br/>"
  reports.generate("/tmp/cars.pdf", "Cars", summary_l, cars_dict_to_table(data))

  # Send the PDF report as an email attachment
  sender = "automation@example.com"
  receiver = "{}@example.com".format(os.environ.get('USER'))
  subject = "Sales summary for last month"
  body = ""
  for elem in summary:
    body = body + elem + "\n"
  message = emails.generate(sender, receiver, subject, body, "/tmp/cars.pdf")
  emails.send(message)


if __name__ == "__main__":
  main(sys.argv)
